# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `RNGtest' in source file `RNGtest.m'.
# Generated by Mercury compiler version 22.01.8-1~jammy
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
RNGtest.optdate RNGtest.trans_opt_date RNGtest.err RNGtest.c_date RNGtest.java_date : \
		RNGtest.m \
	\
		array.int \
		builtin.int \
		int.int \
		io.int \
		list.int \
		private_builtin.int \
		random.int \
		time.int \
		string.format.int \
		string.parse_util.int \
	\
		assoc_list.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		map.int2 \
		maybe.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		RNGtest.int

# RULE mh_and_mih_on_c
RNGtest.mh RNGtest.mih : RNGtest.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
RNGtest.module_dep : jmercury/RNGtest.java

else

# RULE module_dep_on_c
RNGtest.module_dep : RNGtest.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
RNGtest.date RNGtest.date0 : \
		RNGtest.m \
	\
		array.int3 \
		builtin.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		private_builtin.int3 \
		random.int3 \
		time.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
RNGtest.date0 : \
		RNGtest.m \
	\
		array.int3 \
		builtin.int3 \
		int.int3 \
		io.int3 \
		list.int3 \
		private_builtin.int3 \
		random.int3 \
		time.int3 \
		string.format.int3 \
		string.parse_util.int3 \
	\
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		map.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
RNGtest.$O RNGtest.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

# RULE int0_on_date0
RNGtest.int0 : RNGtest.date0
	@:

# RULE int_on_date
RNGtest.int : RNGtest.date
	@:

# RULE int2_on_date
RNGtest.int2 : RNGtest.date
	@:

# RULE int3_on_date3
RNGtest.int3 : RNGtest.date3
	@:

# RULE opt_on_opt_date
RNGtest.opt : RNGtest.optdate
	@:

# RULE trans_opt_on_trans_opt_date
RNGtest.trans_opt : RNGtest.trans_opt_date
	@:

