# vim: ts=8 sw=8 noexpandtab ft=make

# Automatically generated module dependencies for
# module `hello' in source file `Hellotest.m'.
# Generated by Mercury compiler version 22.01.8-1~jammy
# configured for x86_64-pc-linux-gnu.

# RULE date_file_deps
# target group names:
#   dates_and_err
# source group names:
#   (unnamed)
#   long deps
#   short deps
#   type_repn self dep
hello.optdate hello.trans_opt_date Hellotest.err hello.c_date hello.java_date : \
		Hellotest.m \
	\
		builtin.int \
		io.int \
		private_builtin.int \
	\
		array.int2 \
		assoc_list.int2 \
		bitmap.int2 \
		bool.int2 \
		char.int2 \
		construct.int2 \
		deconstruct.int2 \
		enum.int2 \
		list.int2 \
		map.int2 \
		maybe.int2 \
		ops.int2 \
		pair.int2 \
		pretty_printer.int2 \
		stream.int2 \
		string.int2 \
		term.int2 \
		time.int2 \
		tree234.int2 \
		type_desc.int2 \
		univ.int2 \
	\
		hello.int

# RULE mh_and_mih_on_c
hello.mh hello.mih : hello.c

ifeq ($(findstring java,$(GRADE)),java)

# RULE module_dep_on_java
hello.module_dep : jmercury/hello.java

else

# RULE module_dep_on_c
hello.module_dep : hello.c

endif # conditional fragment

# RULE self_and_parent_date_deps
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
hello.date hello.date0 : \
		Hellotest.m \
	\
		builtin.int3 \
		io.int3 \
		private_builtin.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE self_and_parent_date0_deps
# target group names:
#   date0s
# source group names:
#   (unnamed)
#   long dep int3s
#   short dep int3s
hello.date0 : \
		Hellotest.m \
	\
		builtin.int3 \
		io.int3 \
		private_builtin.int3 \
	\
		array.int3 \
		assoc_list.int3 \
		bitmap.int3 \
		bool.int3 \
		char.int3 \
		construct.int3 \
		deconstruct.int3 \
		enum.int3 \
		list.int3 \
		map.int3 \
		maybe.int3 \
		ops.int3 \
		pair.int3 \
		pretty_printer.int3 \
		stream.int3 \
		string.int3 \
		term.int3 \
		time.int3 \
		tree234.int3 \
		type_desc.int3 \
		univ.int3

# RULE foreign_deps_for_mh
hello.$O hello.pic_o : \
		array.mh \
		bitmap.mh \
		io.mh \
		string.mh \
		time.mh

# RULE int0_on_date0
hello.int0 : hello.date0
	@:

# RULE int_on_date
hello.int : hello.date
	@:

# RULE int2_on_date
hello.int2 : hello.date
	@:

# RULE int3_on_date3
hello.int3 : hello.date3
	@:

# RULE opt_on_opt_date
hello.opt : hello.optdate
	@:

# RULE trans_opt_on_trans_opt_date
hello.trans_opt : hello.trans_opt_date
	@:

# RULE date0_on_src
hello.date0 : Hellotest.m
	$(MCPI) $(ALL_GRADEFLAGS) $(ALL_MCPIFLAGS) Hellotest.m

# RULE date_on_src
hello.date : Hellotest.m
	$(MCI) $(ALL_GRADEFLAGS) $(ALL_MCIFLAGS) Hellotest.m

# RULE date3_on_src
hello.date3 : Hellotest.m
	$(MCSI) $(ALL_GRADEFLAGS) $(ALL_MCSIFLAGS) Hellotest.m

# RULE opt_date_on_src
hello.optdate : Hellotest.m
	$(MCOI) $(ALL_GRADEFLAGS) $(ALL_MCOIFLAGS) Hellotest.m

# RULE trans_opt_date_on_src
hello.trans_opt_date : Hellotest.m
	$(MCTOI) $(ALL_GRADEFLAGS) $(ALL_MCTOIFLAGS) Hellotest.m

# RULE c_date_on_src
hello.c_date : Hellotest.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) Hellotest.m $(ERR_REDIRECT)

# RULE java_date_on_src
hello.java_date : Hellotest.m
	$(MCG) $(ALL_GRADEFLAGS) $(ALL_MCGFLAGS) --java-only Hellotest.m $(ERR_REDIRECT)

